version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./www-root:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs

    ports:
      - 8080:80

